Name:           ros-melodic-apriltag-ros
Version:        3.1.1
Release:        1%{?dist}
Summary:        ROS apriltag_ros package

Group:          Development/Libraries
License:        BSD
URL:            http://www.ros.org/wiki/apriltag_ros
Source0:        %{name}-%{version}.tar.gz

Requires:       eigen3-devel
Requires:       opencv-devel
Requires:       ros-melodic-apriltag
Requires:       ros-melodic-cv-bridge
Requires:       ros-melodic-geometry-msgs
Requires:       ros-melodic-image-geometry
Requires:       ros-melodic-image-transport
Requires:       ros-melodic-message-runtime
Requires:       ros-melodic-nodelet
Requires:       ros-melodic-pluginlib
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-sensor-msgs
Requires:       ros-melodic-std-msgs
Requires:       ros-melodic-tf
BuildRequires:  eigen3-devel
BuildRequires:  opencv-devel
BuildRequires:  ros-melodic-apriltag
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-cmake-modules
BuildRequires:  ros-melodic-cv-bridge
BuildRequires:  ros-melodic-geometry-msgs
BuildRequires:  ros-melodic-image-geometry
BuildRequires:  ros-melodic-image-transport
BuildRequires:  ros-melodic-message-generation
BuildRequires:  ros-melodic-nodelet
BuildRequires:  ros-melodic-pluginlib
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-sensor-msgs
BuildRequires:  ros-melodic-std-msgs
BuildRequires:  ros-melodic-tf

%description
A ROS wrapper of the AprilTag 3 visual fiducial detection algorithm. Provides
full access to the core AprilTag 3 algorithm's customizations and makes the tag
detection image and detected tags' poses available over ROS topics (including
tf). The core AprilTag 3 algorithm is extended to allow the detection of tag
bundles and a bundle calibration script is provided (bundle detection is more
accurate than single tag detection). Continuous (camera image stream) and single
image detector nodes are available.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Mon Oct 07 2019 Danylo Malyuta <danylo.malyuta@gmail.com> - 3.1.1-1
- Autogenerated by Bloom

* Sat May 25 2019 Danylo Malyuta <danylo.malyuta@gmail.com> - 3.1.0-1
- Autogenerated by Bloom

